### ISSUE TITLE
Jenkins plugin link opens main page

### ISSUE THREAD

**Issue by goblinmaks** [reportportal/plugin-jenkins#4]
Jenkins plugin link opens main page instead of launch # page.

Link from Jenkins bellow:
https://rp.my.com/#TestProject/launches/all?page.page=1&page.size=50/599c3630b9d82100074dd1c0

**Comment by avarabyeu** [comment]
@pictureb00k need to check it

**Comment by pbortnik** [comment]
fixed

**Comment by goblinmaks** [comment]
Latest version will be uploaded to Jenkins plugin repo ?
