### ISSUE TITLE
How do I actually configure and use the plugin

### ISSUE THREAD

**Issue by EricLSD** [reportportal/plugin-jenkins#5]
I have installed the plugin, as available from the Jenkins plugin page (instead of building from source).  In installing 0.5 of the report portal plugin and restarting Jenkins I am unclear where to go next.  The only place I see an option for configuring or using the plugin is from the post-build actions.  Here I have configured:

Rest endpoint: http://reportportal_example:8080/ui/#api
Project: test_project

When I click check connection I get a successful message; however, when I run the build ('build now') the job will fail and no results are posted.   The Readme.md file is a bit lacking here, can you provide any additional details on where to go next.

**Comment by pbortnik** [comment]
What do you see in logs of your job build?

**Comment by talmoshe** [comment]
What do I put in Launch and Token fields?

**Comment by DzmitryHumianiuk** [comment]
@SiarheiDubovik can you plz assist?

**Comment by DzmitryHumianiuk** [comment]
@eanxgeek did you resolve your issue?

**Comment by eanxgeek** [comment]
I have not had a chance to try again, I'll see if I can test again.

**Comment by navinchandrac** [comment]
Need steps by steps information, How to configure and use the ReportPortal Jenkins plugin.

**Comment by ShivaPotlapelli** [comment]
Hey DzmitryHumianiuk,

Can you please assist in c configure and use the ReportPortal Jenkins plugin.

**Comment by DzmitryHumianiuk** [comment]
@ShivaPotlapelli https://www.youtube.com/watch?v=jqzFfVV0OvM
first 30 seconds.
nothing changed from that time.

**Comment by DzmitryHumianiuk** [comment]
plugin is pretty outdated.
we might think of `killing` it.

**Comment by katcaola** [comment]
@DzmitryHumianiuk Would you write another plugin that is more up to date? 
What reasons are there for deprecating it?

**Comment by DzmitryHumianiuk** [comment]
@katcaola there is no such a plans.

The reason it has super low priority is simple: it doesn't bring much of benefits.

In a meanwhile, users realizes that they don't need it at all, since they check results right in ReportPortal. And don't need this step in the middle, to see results at Jenkins page.
If feel like you are missing it, because you still have a habit to see results at Jenkins pages first.

When you go deeper with RP usage, you check results only in RP, skipping Jenkins pages. Cause you need Jenkins only to execute the job.

The next level of adaptation will be understanding that you you want to call Jenkins actions from ReportPortal screen.
That is the moment when such type of requests appears https://github.com/reportportal/reportportal/issues/143

that's why we focusing on features in RP, rather then on Jenkins plugin.

**Comment by katcaola** [comment]
@DzmitryHumianiuk Does this mean you don't need to install the jenkins plugin, if you want to send results/logs from a jenkins build to RP?

**Comment by DzmitryHumianiuk** [comment]
@katcaola yes, it is.
there is no need in any jenkins plugin.

RP adapter connects to test cases (testing engine, like junit, testNG, nunit, etc.)
And there is no any difference where you execute results, at local env, remote env, or with jenkins.

RP adapter will send data directly into RP server.

**Comment by katcaola** [comment]
@DzmitryHumianiuk Are there any READMEs or examples of the RP adapter that I can read about?
Thanks :smiley:

**Comment by DzmitryHumianiuk** [comment]
@katcaola 
https://reportportal.io/download 
section 4

click required agent. it will lead to github page with instructions

**Comment by dbisht29** [comment]
I am also facing the same issue. Connection is successful but when I build the job status is marked as failure and no results are posted. Any update on this issue ?

**Comment by jainriteshkumar17** [comment]
can someone share the download link for the plugin

**Comment by DzmitryHumianiuk** [comment]
https://mvnrepository.com/artifact/org.jenkins-ci.plugins/reportportal?repo=springio-plugins-release

**Comment by Manoj0251** [comment]
> I am also facing the same issue. Connection is successful but when I build the job status is marked as failure and no results are posted. Any update on this issue ?

Can anyone help me with the issue ?

**Comment by DzmitryHumianiuk** [comment]
it's outdated and deprecated.

you don't need it to run tests.
