### ISSUE TITLE
Error in Jenkins while publishing results to ReportPortal "Build step 'ReportPortal Results Publisher' marked build as failure" but Results are getting published to Report Portal

### ISSUE THREAD

**Issue by Manoj0251** [reportportal/plugin-jenkins#8]
I tired integrating the Jenkins with ReportPortal, generated the latest plugin and added to Jenkins.
After execution Not sure why the below error message is displayed 
**"Build step 'ReportPortal Results Publisher' marked build as failure"**
And the build is marked as failed. But the Results are getting pushed to ReportPortal and in the Jenkins as well the details are displayed .
And Report Portal Results Chart is also updated 
******************************************************************************************************
![Jenkins](https://user-images.githubusercontent.com/17288291/69398947-4962b700-0d12-11ea-8122-e3f36210f850.PNG)
****************************************************************************************************
![Jenkins2](https://user-images.githubusercontent.com/17288291/69398946-48ca2080-0d12-11ea-8950-a4213bd71d9a.PNG)
*******************************************************************************************************
![Jenkins3](https://user-images.githubusercontent.com/17288291/69398945-48ca2080-0d12-11ea-9c53-40b93a8c852d.PNG)

**Comment by DzmitryHumianiuk** [comment]
@Manoj0251 first of all - plugin is obsolete
https://github.com/reportportal/plugin-jenkins/blob/master/README.md#-jenkins-plugin-obsolete-team-does-not-support-at-the-moment

You don't need Jenkins plugin in order to receive results in ReportPortal server.
ReportPortal integration works at test runner level.

**my suggestion: delete plugin.**
